lxn/walk

bitmap.go
customwidget.go
window.go

I changed the method name from Image to Screenshot, because Image conflicts with properties of some types which implement a window.
Most worked out of the box, by sending the WM_PRINT command, however everything depending on CustomWidget (Canvas, ImageView) needed additions to WndProc.
The background is described here:
http://www.fengyuan.com/article/wmprint.html
Closes #190

add screenshot api

---

dialog.go

If a small main window is moved to the top/side/bottom of the screen, and it uses larger dialogs, then the dialogs are opened so that they hang off the screen.
This PR changes Dialog.Show so that the dialog appears completely on the screen even in this case.

dialog: avoid dialog hanging off screen when possible

---

form.go

add Activating/Deactivating events to Form

---

label.go

Add GrowableHorz to Label to allow aligning

---

gridlayout.go

Width and Height must be strictly positive.

Fix grid layout rectangle bounds check

---

tableview.go

The -1 convention is the same as what the win32 API takes.

tableview: allow efficiently selecting all indices

---

notifyicon.go

This also fixes panic when info or title are empty.
Depends-on: https://github.com/lxn/win/pull/68
Resolves: https://github.com/lxn/walk/pull/232

notifyicon: allow showing custom icons and receiving balloon clicks

---

form.go

See https://github.com/lxn/win/pull/76

form: lock OS thread in message loop

---

tableview.go

This is @adongy's commit. Seems to work quite well.

tableview: allow empty space handling

---

form.go

This is a filthy hack but is better than installing a message filter on the tray area handle.

notifyicon: delay DPI update by one second

---

canvas.go
window.go

canvas: measure font height at real DPI

---

window.go

We still need to store the last DPI for the scaling calculation,
however, so rename the dpi member to match what it is.

window: don't cache DPI

---

AUTHORS
examples/notifyicon/notifyicon.go

Fix not enough arguments in call to ni.ShowCustom

---

form.go
mainloop_cgo.go
mainloop_default.go

mainloop: add optional C implementation

---

AUTHORS
tableview.go

This PR extends TableView with LVS_EX_GRIDLINES support.

TableView: Add support for gridline toggling

---

examples/externalwidgets/externalwidgets.go

This doesn't fix the other issue with this regarding CreateLayoutItem,
but somebody can handle that in a different PR.

examples/externalwidgets: use MustRegister properly

---

window.go

This reverts commit 0bdcba701d40ae92ef8e1e65ccd14c125f28e9c3.
Until issue #623 is addressed, this is gone.

Revert "Add support for Dynamic Annotation"

---

size.go
tabwidget.go

@lxn, you just beat me by merging the #627 while I was reviewing the TabWidget.
This is what I was working on.

DPI Fun v3

---

metafile.go
util.go

Metafile, DPI: Cleanup

---

canvas.go

The "dpi fun v2" patchset from @rozmansi forgot to check back references.

image: cleanup stale interface function name

---

icon.go

Legacy LoadImage() picks a smaller icon variant and scales it up when the desired size is not available. LoadIconWithScaleDown() introduced in Windows Vista picks a larger icon variant and scales it down producing slightly better results.

Icon: Switch to LoadIconWithScaleDown()

---

AUTHORS
treeview.go

I don't know whether this is the correct fix, but I can confirm that this appears to resolve the issue.

remove treeview condition check
